---
abstract: 'Catalyst session plugin via Starch.'
author:
  - 'Aran Deltac <bluefeet@gmail.com>'
build_requires:
  Test::Fatal: '0'
  Test::Simple: '0.96'
  Test::WWW::Mechanize::PSGI: '0.35'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.037, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-Plugin-Starch
requires:
  Catalyst: '5.90001'
  Class::Method::Modifiers: '2'
  Moose: '2'
  MooseX::ClassAttribute: '0.27'
  Starch: '0.03'
  Type::Tiny: '1.000005'
  namespace::clean: '0.24'
  strictures: '2'
resources:
  bugtracker: https://github.com/bluefeet/Catalyst-Plugin-Starch/issues
  repository: git://github.com/bluefeet/Catalyst-Plugin-Starch.git
version: '0.03'
